apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-nginx-ingress
spec:
  ingressClassName: ingress-traefik
  rules:
    - host: library-dev.productdock.rs
      http:
        paths:
          - path: /simple-nginx
            pathType: Prefix
            backend:
              service:
                name: nginx
                port:
                  name: http
